### ISSUE TITLE
Roadmap for 8.0.0

### ISSUE THREAD

**Issue by sethmlarson** [elastic/enterprise-search-python#105]
Collecting all the items left to complete before an 8.0.0 release can be created.

- [x] Switch to new API generator (https://github.com/elastic/enterprise-search-python/pull/100)
- [x] Deprecate `body`, `params` and transport parameters (https://github.com/elastic/enterprise-search-python/pull/108)
- [x] Change parameters to be keyword-only (https://github.com/elastic/enterprise-search-python/pull/100)
- [x] `enterprise_search.get_stats` `include` parameter serialization (https://github.com/elastic/enterprise-search-python/pull/117)
- [x] Add new test cases for async clients (https://github.com/elastic/enterprise-search-python/pull/111)
- [x] Check that a correct version of elastic-transport is installed (https://github.com/elastic/enterprise-search-python/pull/120)
- [x] Add proper type hints for responses (https://github.com/elastic/enterprise-search-python/pull/123)

**Comment by sethmlarson** [comment]
There is now a pre-release of 8.1.0 available: https://github.com/elastic/enterprise-search-python/releases/tag/v8.1.0a1
